# workflow derrived from https://stackoverflow.com/a/71489231 and
# https://github.com/ropensci/allcontributors/blob/main/.github/workflows/allcontributors.yml
# we want to be a dependency of R-CMD-check.yaml so this will run first

name: Update-allcontributors
on: [workflow_call]

jobs:
  allcontributors:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Update allcontributors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 5

      - name: Update allcontributors
        id: need_commit
        run: |
          rc=`Rscript -e "any(allcontributors::add_contributors())"`
          echo "return_code=$rc" >> $GITHUB_OUTPUT

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "The return code was ${{ steps.need_commit.outputs.return_code }}"

      - name: Commit on change
        if: ${{ contains(steps.need_commit.outputs.return_code, 'TRUE') }}
        run: |
          git config user.name  "Github Actions"
          git config user.email "github-actions@github.com"
          git commit README.md -m 'Update allcontributors on README.Rmd'
          git push https://${{github.actor}}:${{github.token}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }}
