# workflow derrived from https://stackoverflow.com/a/71489231 and
# https://github.com/ropensci/allcontributors/blob/main/.github/workflows/allcontributors.yml
# we want to be a dependency of R-CMD-check.yaml so this will run first

name: Update-allcontributors
on: [workflow_call]

jobs:
  allcontributors:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Update allcontributors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 5

      - name: Install allcontributors package
        run: R CMD INSTALL .

      - name: Update allcontributors
        id: need_commit
        run: Rscript -e 'any(allcontributors::add_contributors())'

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Commit results
        run: |
          git config user.name  "Github Actions"
          git config user.email "github-actions@github.com"
          git commit README.md -m 'Update allcontributors on README.Rmd' || echo "No changes to commit"
          git push https://${{github.actor}}:${{github.token}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"

